### ISSUE TITLE
Getting error on building site

### ISSUE THREAD

**Issue by soumyamaity** [hugo-themes/toha#760]
hugo server --theme toha --watch

Start building sites … 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\application.js:2:7": Could not resolve "bootstrap"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\application.js:3:7": Could not resolve "@fortawesome/fontawesome-free/js/all"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\features\darkmode\darkreader.js:1:54": Could not resolve "darkreader"      
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\features\flowchart\mermaid.js:1:20": Could not resolve "mermaid"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\features\math\katex.js:1:32": Could not resolve "katex/contrib/auto-render"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\features\syntaxhighlight\hljs.js:1:17": Could not resolve "highlight.js"   
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\features\videoplayer\plyr.js:1:17": Could not resolve "plyr"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\pages\home.js:1:21": Could not resolve "ityped"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\pages\note.js:1:25": Could not resolve "imagesloaded"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\pages\search.js:1:17": Could not resolve "fuse.js"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\pages\search.js:2:17": Could not resolve "mark.js"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\sections\projects.js:1:22": Could not resolve "filterizr"
ERROR 2023/05/15 16:13:30 js.Build failed: "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\sections\publications.js:1:22": Could not resolve "filterizr"
ERROR 2023/05/15 16:13:30 JSBUILD: failed to transform "scripts/application.js" (text/javascript): "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\scripts\application.js:1:7": Could not resolve "popper.js"
Error: Error building site: TOCSS: failed to transform "styles/application.scss" (text/x-scss): "C:\Users\soumy\git\myWebsite\mysite\themes\toha\assets\styles\application.template.scss:3:1": File to import not found or unreadable: bootstrap/scss/bootstrap.
Built in 107 ms

**Comment by mmzeynalli** [comment]
Did you install necessary npm packages?

**Comment by soumyamaity** [comment]
Now it is working after installing the npm packages....
It would be great if these steps can be added in documentation page https://toha-guides.netlify.app/posts/getting-started/prepare-site/

hugo mod tidy
hugo mod npm pack
npm install
