### ISSUE TITLE
The pagination for bigger screens works wrong

### ISSUE THREAD

**Issue by mmzeynalli** [hugo-themes/toha#886]
## Expected Behavior
In the posts page, the posts should be gridded by 5,5,5 and the next page button.

## Current Behavior
It shows 5, 5, 2 and the next page.

### Screenshots
![image](https://github.com/hugo-toha/toha/assets/33568903/264a4edb-942c-4fe8-aff2-0a53d4e234ba)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

I have 32'' screen, 2560x1440 resolution. Using MacOS, Edge browser.

**Comment by hossainemruz** [comment]
You can configure how many posts will be shown per page. By default, it is 12. If you set higher number then it will show more cards. You have to set the `pagination.maxPostsPerPage` variable in your config.yaml file. Check this example:
https://github.com/hugo-toha/hugo-toha.github.io/blob/81444d2c7e65fc3ea31dcb75396d86bf834a1e50/config.yaml#L259

**Comment by hossainemruz** [comment]
Feel free to re-open if you still having trouble setting pagination.
